### ISSUE TITLE
Cool...but relationships?

### ISSUE THREAD

**Issue by fabiosoft** [j-burgos/Flask-DbSeeder#1]
How can i assign a relationship?

for example i have a User model with assigned posts... how can i relate them in `add_seed` method?

``` python
 seeder = Seeder(database)
    seeder.add_seed([
        User(username='john', password_hash=hp.make_hash('psw')),
        User(username='mickey', password_hash=hp.make_hash('psw')),

        Post() # ???
    ])
    seeder.run()
```

**Comment by j-burgos** [comment]
Hello @fabiosoft, thank you for your interest in this tool!
Depending on your `User` model, you could add the related posts to a user like this:

``` python
    seeder.add_seed([
        User(username='john', password_hash=hp.make_hash('psw'), posts=[Post(), Post()]),
    ...
```

**Comment by fabiosoft** [comment]
Worked like a charm!
Thanks so much
